server:
  port: 8000

#SQL日志输出，线上需要去掉这配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xunmiao_db
    username: caizhilong
    password: abcd1234